### PR TITLE
update instance type - fix #5

### LINKED ISSUE #5: update instance type
https://github.com/moka-guys/dnanexus_mokapicard/blob/7fe21e70cf2617701aa156ba951496858a9f14b3/dxapp.json#L91

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/6)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/6)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/6#-NRIU7Y5ByRt3qiIAxSO:-NRIU7Y5ByRt3qiIAxSP:b-lta34y) (no related file):*
Suggestion to remove the version number from the readme file - this is not needed as version can be seen by the tag / release, and adds another thing to remember to change which is unnecessary and can be easily missed / not noticed

___

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/6)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/6#-NRIU7Y5ByRt3qiIAxSO:-NRIbRUrEFNSDvimgWaL:b-896fix) (no related file):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Suggestion to remove the version number from the readme file - this is not needed as version can be seen by the tag / release, and adds another thing to remember to change which is unnecessary and can be easily missed / not noticed
</blockquote></details>

Done.

___

**Review by RachelDuffin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Review by RachelDuffin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
