### PR TITLE
mokapicard dna nexus app v1.0

### PR DESCRIPTION
**Pull request by NMNS93**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokapicard/1)

### CODE REVIEW

**Comment by AmyAmelia** [comment]
Claimed :) 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-:-L2dwUIwkaTr3gb1gyT4:b-hg9hyx)*

**Comment by AmyAmelia** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[README.md, line 11 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e-TI2VnbnDLXB67YK:-L2e-TI2VnbnDLXB67YL:b-6p0b8j) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L11)):*
> ```Markdown
> 
> ## What are typical use cases for this app?
> This app is designed to be run either standalone or as part of a DNA Nexus workflow. 
> ```

You should clarify/ expand on this sentence, why should we used it and on what data? eg. " This app is designed to be run on aligned sequencing data, either as a standalone app or as part of a DNA Nexus workflow." 
you could perhaps provide an example of the workflow in which its used (MokaWES) .
Have a look some of the other read me for inspiration (https://github.com/moka-guys/dnanexus_fastqc). 

---

*[README.md, line 12 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2dzZsb3RGVXoju-laI:-L2dzZsb3RGVXoju-laJ:bda81fj) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L12)):*
> ```Markdown
> ## What are typical use cases for this app?
> This app is designed to be run either standalone or as part of a DNA Nexus workflow. 
> The outputs of this app are to be displayed visually using [MultiQC](http://multiqc.info/).
> ```

Perhaps you should mention that this app combines/ replaces the need for the individual Moka vendor and Picard collect multiple metrics apps.

---

*[README.md, line 16 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e2Vt5Q45bKnhwsXGo:-L2e2Vt5Q45bKnhwsXGp:bwu5jvd) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L16)):*
> ```Markdown
> ## What data are required for this app to run?
> The following command-line arguments are required for this app to run:
> ```

List the files that app needs rather than the arguments. 
This is a little miss leading as it suggests we have to give the app the command line arguments in the specific following format, when in fact we give the app the files and the code makes the arguments. Have a look some of the other read me's for inspiration (https://github.com/moka-guys/dnanexus_fastqc or or https://github.com/moka-guys/dnanexus_vardict ). 

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e4L6wBVQj_DDT0xnz:-L2e4L6xvp7eJVLEPSCq:brrj7vo) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L44)):*
> ```Markdown
> 
> ## How does this app work?
> This app downloads the provided inputs, then calls Picard CollectMultipleMetrics and Picard CalculateHsMetrics using the sorted BAM file as input. Finally, the output files provided by both Picard modules are uploaded to a 'QC/' directory.
> ```

I'm being pedantic here but you could be a little more concise:
All output files are uploaded to a 'QC/' directory.

---

*[src/code.sh, line 8 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e7qCTXtTeTV4PqLX5:-L2e7qCTXtTeTV4PqLX6:b-3rj1f0) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L8)):*
> ```Shell
> 
> collect_multiple_metrics() {
> 	# Call Picard CollectMultipleMetrics
> ```

describe in the comments what input file this need

---

*[src/code.sh, line 16 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e8k3ynh2Cw9ZmS6yW:-L2e8k3ynh2Cw9ZmS6yX:bb7r2f0) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L16)):*
> ```Shell
> 
> calculate_hs_metrics() {
> 	# Set prefix for file containing geneome target regions using names of input files
> ```

why?

---

*[src/code.sh, line 18 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e8m4rKx41w1tPdZNU:-L2e8m4rKx41w1tPdZNV:b5wmhav) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L18)):*
> ```Shell
> 	# Set prefix for file containing geneome target regions using names of input files
> 	targets=${vendor_exome_bedfile_prefix}_${fasta_index_prefix}_targets
> 	# Prepare genome regions from input bam file
> ```

what regions?

---

*[src/code.sh, line 25 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e88LeGtaowOw2-Ecx:-L2e88LeGtaowOw2-Ecy:bzaasz9) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L25)):*
> ```Shell
> 	awk '{print $1 "\t" $2+1 "\t" $3 "\t+\t" $1 ":" $2+1 "-" $3}' < tidied.bed >> $targets.picard
> 
> 	# Run Picard CalculateHsMetrics
> ```

So does this use the output from the first function? Please expand on the comments. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1)*

**Comment by AmyAmelia** [comment]
+@amyamelia 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-:-L2e9XaTbaMUXSboBRud:b-z3lu1q)*

**Comment by NMNS93** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[README.md, line 11 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e-TI2VnbnDLXB67YK:-L2eQhnxOuNAYZJOj05Y:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L11)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

You should clarify/ expand on this sentence, why should we used it and on what data? eg. " This app is designed to be run on aligned sequencing data, either as a standalone app or as part of a DNA Nexus workflow." 
you could perhaps provide an example of the workflow in which its used (MokaWES) .
Have a look some of the other read me for inspiration (https://github.com/moka-guys/dnanexus_fastqc). 

</blockquote></details>

Done.

---

*[README.md, line 12 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2dzZsb3RGVXoju-laI:-L2eQiNrWK6j2JZqVjOP:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L12)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

Perhaps you should mention that this app combines/ replaces the need for the individual Moka vendor and Picard collect multiple metrics apps.
</blockquote></details>

Done.

---

*[README.md, line 16 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e2Vt5Q45bKnhwsXGo:-L2eQj4a9Xmdzwnpe8-X:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L16)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

List the files that app needs rather than the arguments. 
This is a little miss leading as it suggests we have to give the app the command line arguments in the specific following format, when in fact we give the app the files and the code makes the arguments. Have a look some of the other read me's for inspiration (https://github.com/moka-guys/dnanexus_fastqc or or https://github.com/moka-guys/dnanexus_vardict ). 
</blockquote></details>

Done.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e4L6wBVQj_DDT0xnz:-L2eNSOTp73eqQLnWmwf:blie5g7) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L44)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

I'm being pedantic here but you could be a little more concise:
All output files are uploaded to a 'QC/' directory.
</blockquote></details>

pedantic is better :smile: 

---

*[src/code.sh, line 8 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e7qCTXtTeTV4PqLX5:-L2eQklTUGqZzCgsixC2:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L8)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

describe in the comments what input file this need
</blockquote></details>

Done.

---

*[src/code.sh, line 16 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e8k3ynh2Cw9ZmS6yW:-L2eTp2GdCC5D5UqNIzB:btd51a6) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L16)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

why?
</blockquote></details>

I agree.

---

*[src/code.sh, line 18 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e8m4rKx41w1tPdZNU:-L2eTo0zqI1wtNKD2U-x:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L18)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

what regions?
</blockquote></details>

Done.

---

*[src/code.sh, line 25 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e88LeGtaowOw2-Ecx:-L2eQogmwWJjWIM8DwaI:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/src/code.sh#L25)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

So does this use the output from the first function? Please expand on the comments. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1)*

**Comment by AmyAmelia** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e4L6wBVQj_DDT0xnz:-L2edk8RgAy0g8XpZU8B:b-ewpbr3) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L44)):*
<details><summary><i>Previously, NMNS93 wrote…</i></summary><blockquote>

pedantic is better :smile: 
</blockquote></details>

I wouldn't mention the term both Picard modules as you have previously been  referring to the whole app (unless there are other outputs from this app and only the picard modules are going into /QC. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1)*

**Comment by AmyAmelia** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1)*

**Comment by NMNS93** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-L2e4L6wBVQj_DDT0xnz:-L2ehXpHeEMkMQkGwm62:blfhb6r) ([raw file](https://github.com/moka-guys/dnanexus_mokapicard/blob/91e5e882e1722cd6bd4991c592245716d4f494ef/README.md#L44)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

I wouldn't mention the term both Picard modules as you have previously been  referring to the whole app (unless there are other outputs from this app and only the picard modules are going into /QC. 
</blockquote></details>

finito!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1)*

**Comment by AmyAmelia** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1#-:-L2ej8M5r3UevFpCDzfW:bnfp4nl)*

**Comment by AmyAmelia** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_mokapicard/1)*

**Pull request merged**
